### ISSUE TITLE
Support for MathOptInterface

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Pavito.jl#7]

**Comment by kaarthiksundar** [comment]
Any update on this issue?

**Comment by chriscoey** [comment]
I'm waiting on jump 0.19 and MIP callbacks and some progress on MINLPTests

**Comment by odow** [comment]
- JuMP 0.19 : in progress. ETA JuMP-dev
- MIP callbacks: https://github.com/JuliaOpt/Gurobi.jl/pull/194
- MINLPTests: https://github.com/lanl-ansi/MINLPTests.jl/pull/8

**Comment by odow** [comment]
Okay, so here is a proposal for how this could look. First, two non-negotiables:
1. Pavito needs "solver-independent" callbacks. 
2. We don't want to have PavitoGurobi.jl, PavitoCPLEX.jl, PavitoGLPK.jl etc

So, Pavito defines it's own "callback API", and then implements a set of modules that contain the solver-specific API.

Just like in JuliaOpt/Gurobi.jl#194, these are loaded via special macros.
```julia
using Pavito
Pavito.@using Gurobi
Pavito.@using GLPK
```

**Comment by chriscoey** [comment]
Thanks for thinking about this @odow. 
So what if Pavito and Pajarito (and DaChoppa, etc etc) all use these callbacks in very similar ways? Would we be duplicating a lot of code?

**Comment by odow** [comment]
You should make a `JuMPCallbacks` package with a well-defined API that contains the solver-specific modules. That way, you get fine-grained control over how the callbacks are implemented in each solver for your application.

General users could use this package if they accept the limited API (e.g., lazy constraints are only applied at integer nodes when conditions X and Y are met).

It's a first-step towards re-introducing solver-independent callbacks.

**Comment by odow** [comment]
See also https://github.com/JuliaOpt/GLPK.jl/pull/91. 

I'm beginning to develop a plan that goes directly towards my `JuMPCallbacks` package. Given the similarities between GLPK, Gurobi, and CPLEX, I think it's do-able.

**Comment by chriscoey** [comment]
Yaaas excellent

**Comment by odow** [comment]
See https://github.com/JuliaOpt/Gurobi.jl/pull/194#issuecomment-462202113

This is prototyped and working.

**Comment by linde-fr** [comment]
Am I right to conclude that Pavito can not yet be used with JuMP >=v0.19 ?

**Comment by odow** [comment]
Correct. Callbacks have been re-introduced into JuMP, so we just need someone to put in the effort of converting the code.

**Comment by linde-fr** [comment]
Thanks for your reply! I would like to help out but am not sure of how much help I can be. If you can give me some directions perhaps I can

**Comment by spockoyno** [comment]
Might there be a quick and dirty solution before Pavito is updated to Jump 0.19+?

Background: I have experiment optimisation code using Pavito with CPLEX  in Julia 0.7. I’m extending it to dose selection in  vaccine trials. Ideally, I’d upgrade to Julia 1.4 and some new packages. So what could be the quickest way?

**Comment by mlubin** [comment]
A couple options:
1. JuMP 0.18 is compatible with Julia 1.0. It's probably not that hard to get Pavito + JuMP 0.18 working on Julia 1.4.
2. Pavito is essentially equivalent to certain configurations of Bonmin, which you can run with the latest version of JuMP via AmplNLWriter. If you compile Bonmin manually, there's an option to link it to CPLEX.

**Comment by ccoffrin** [comment]
Juniper is also an alternative for MINLP, which is compatible with JuMP v0.19.  It could provide a stopgap until Pavito is updated.

**Comment by spockoyno** [comment]
Thanks! I'll try these solutions.
